export const RESTROOMS = [
  {
    id: "walc-1",
    building: "WALC",
    floor: "1",
    singleStall: false,
    accessible: true,
    genderNeutral: false,
    recentTraffic: "Moderate",
    lat: 40.4275,
    lng: -86.9132,
    direction: "North Wing",
    landmark: "Near main stairwell",
  },
  {
    id: "hicks-2",
    building: "HICKS",
    floor: "2",
    singleStall: true,
    accessible: true,
    genderNeutral: true,
    recentTraffic: "Empty",
    lat: 40.4265,
    lng: -86.9115,
    direction: "North Wing",
    landmark: "Near main stairwell",
  },
  {
    id: "pmu-1",
    building: "PMU",
    floor: "1",
    singleStall: false,
    accessible: true,
    genderNeutral: false,
    recentTraffic: "Busy",
    lat: 40.4249,
    lng: -86.9139,
    direction: "North Wing",
    landmark: "Near main stairwell",
  },
  {
    id: "stewart-1",
    building: "Stewart Center",
    floor: "1",
    singleStall: false,
    accessible: true,
    genderNeutral: false,
    recentTraffic: "Moderate",
    lat: 40.4276,
    lng: -86.9125,
    direction: "North Wing",
    landmark: "Near main stairwell",
  },
  {
    id: "krannert-1",
    building: "Krannert",
    floor: "1",
    singleStall: false,
    accessible: true,
    genderNeutral: false,
    recentTraffic: "Busy",
    lat: 40.4237,
    lng: -86.9212
  },
  {
    id: "lawson-2",
    building: "Lawson",
    floor: "2",
    singleStall: true,
    accessible: true,
    genderNeutral: true,
    recentTraffic: "Empty",
    lat: 40.4274,
    lng: -86.9167
  },
  {
    id: "corec-1",
    building: "CoRec",
    floor: "1",
    singleStall: false,
    accessible: true,
    genderNeutral: false,
    recentTraffic: "Moderate",
    lat: 40.4233,
    lng: -86.9210
  },
  {
    id: "pmu-2",
    building: "PMU",
    floor: "2",
    singleStall: true,
    accessible: true,
    genderNeutral: false,
    recentTraffic: "Moderate",
    lat: 40.4249,
    lng: -86.9139
  },
  {
    id: "hicks-1",
    building: "Hicks",
    floor: "1",
    singleStall: false,
    accessible: true,
    genderNeutral: false,
    recentTraffic: "Busy",
    lat: 40.4265,
    lng: -86.9115
  },
  {
    id: "beering-1",
    building: "Beering Hall",
    floor: "1",
    singleStall: false,
    accessible: true,
    genderNeutral: false,
    recentTraffic: "Moderate",
    lat: 40.4257,
    lng: -86.9144
  },
  {
    id: "armstrong-1",
    building: "Armstrong Hall",
    floor: "1",
    singleStall: true,
    accessible: true,
    genderNeutral: true,
    recentTraffic: "Empty",
    lat: 40.4293,
    lng: -86.9138
  },
  {
    id: "msee-1",
    building: "MSEE",
    floor: "1",
    singleStall: false,
    accessible: true,
    genderNeutral: false,
    recentTraffic: "Moderate",
    lat: 40.4289,
    lng: -86.9149
  },
  {
    id: "forney-1",
    building: "Forney Hall",
    floor: "1",
    singleStall: false,
    accessible: true,
    genderNeutral: false,
    recentTraffic: "Busy",
    lat: 40.4272,
    lng: -86.9159
  },
  {
    id: "rawls-1",
    building: "Rawls Hall",
    floor: "1",
    singleStall: true,
    accessible: true,
    genderNeutral: true,
    recentTraffic: "Empty",
    lat: 40.4230,
    lng: -86.9204
  },
  {
    id: "physics-1",
    building: "Physics Building",
    floor: "1",
    singleStall: false,
    accessible: true,
    genderNeutral: false,
    recentTraffic: "Moderate",
    lat: 40.4297,
    lng: -86.9132
  },
  {
    id: "math-1",
    building: "Math Building",
    floor: "1",
    singleStall: false,
    accessible: true,
    genderNeutral: false,
    recentTraffic: "Busy",
    lat: 40.4260,
    lng: -86.9151
  },
  {
    id: "cl50-1",
    building: "CL50",
    floor: "1",
    singleStall: false,
    accessible: true,
    genderNeutral: false,
    recentTraffic: "Moderate",
    lat: 40.4279,
    lng: -86.9164
  },
  {
    id: "young-1",
    building: "Young Hall",
    floor: "1",
    singleStall: false,
    accessible: true,
    genderNeutral: false,
    recentTraffic: "Busy",
    lat: 40.4268,
    lng: -86.9141
  },
  {
    id: "brown-1",
    building: "Brown Building",
    floor: "1",
    singleStall: true,
    accessible: true,
    genderNeutral: true,
    recentTraffic: "Empty",
    lat: 40.4280,
    lng: -86.9156
  }
]
